### ISSUE TITLE
Downloading APK already purchased on play.google.com

### ISSUE THREAD

**Issue by nilayprukash97** [dweinstein/node-google-play#10]
I can't seem to download an APK I have already purchased at the play store.

The appDeliveryData of the purchaseStatusResponse is null.

Any help appreciated...

**Comment by dweinstein** [comment]
currently this code doesn't support purchased apps. it might be something I add support for in the future.

**Comment by MisteFr** [comment]
Is that still a WIP ?

**Comment by dweinstein** [comment]
This works.
