### ISSUE TITLE
DF-DFERH-01

### ISSUE THREAD

**Issue by rgpronaldo** [dweinstein/node-google-play#100]
i have a problem ,if android is right ,the problem is 
:"Unhandled rejection RequestError: Error retrieving information from server. DF-DFERH-01
",but androidId is wrong as '123456',some apks can download,but some apks have problme:"Unhandled rejection RequestError: Your device is not compatible with this item.",
can you help me?thanks!

**Comment by poi5305** [comment]
I think this issue is same as this [issue](https://github.com/dweinstein/node-google-play/issues/101).
androidId, apiUserAgent or downloadUserAgent is not correct.
