### ISSUE TITLE
Google changes

### ISSUE THREAD

**Issue by AviFix** [dweinstein/node-google-play#101]
Hi

Thanks for the great app.

It looks like google changed something.

version and more data is no longer returnd (example: com.groboot.mdaemergency).

Please see if you can fix it

Thanks

**Comment by dweinstein** [comment]
works for me, check your username/password/android_id you're using https://github.com/dweinstein/node-google-play#id-and-user-agent

**Comment by poi5305** [comment]
I had same problem, too.
But after I use the correct `androidId`, `apiUserAgent` and `downloadUserAgent` fetch form `mitmproxy`. Every thing works fine.

**Comment by bqio** [comment]
What should I do to get a user-agent?

I only get Android-Finsky / 15.8.23-all [0] [PR] 259261889, but it is different from yours.

**Comment by AviFix** [comment]
It seems that google play no longer works through a proxy.

When I routed the traffic via mitmproxy the google play app cant communicate with its server (Other apps can)

**Comment by poi5305** [comment]
I just used `mitmproxy`, and it works fine.
Tested on [nox](https://www.bignox.com/) emulator (mac version)

I think you cloud use my agent. I test on two different nox emulators and the agent is the same, but deviceId is different. You should find deviceId yourself.

apiUserAgent
`Android-Finsky/15.8.23-all%20%5B0%5D%20%5BPR%5D%20259261889 (api=3,versionCode=81582300,sdk=22,device=samsung,hardware=shamu,product=dream2qltezh,platformVersionRelease=5.1.1,model=SM-G9550,buildId=LYZ28N,isWideScreen=0,supportedAbis=x86;armeabi-v7a;armeabi)`

downloadUserAgent
`AndroidDownloadManager/5.1.1 (Linux; U; Android 5.1.1; XT1570 Build/LYZ28N)`

![螢幕快照 2019-08-04 下午11 50 38](https://user-images.githubusercontent.com/1979487/62426305-a3188480-b715-11e9-84fa-1a64ec8fd474.png)
![螢幕快照 2019-08-04 下午11 51 47](https://user-images.githubusercontent.com/1979487/62426308-a6ac0b80-b715-11e9-94c7-963dac4c64ec.png)
