### ISSUE TITLE
Help!!!!!! LoginError

### ISSUE THREAD

**Issue by keyofd** [dweinstein/node-google-play#103]
{ response: 
   { debugId: 1,
     headers: 
      { 'content-type': 'text/plain; charset=utf-8',
        'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        pragma: 'no-cache',
        expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
        date: 'Thu, 29 Aug 2019 11:42:19 GMT',
        'content-encoding': 'gzip',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        server: 'GSE',
        'alt-svc': 'quic=":443"; ma=2592000; v="46,43,39"',
        connection: 'close',
        'transfer-encoding': 'chunked' },
     statusCode: 404,
     body: 'Error=UNKNOWN_ERR' } }
{"message":"Error=UNKNOWN_ERR","name":"LoginError"}

**Comment by shibataism** [comment]
I'm having the same issue. This started couple hours ago.
This looks wired as sometimes I got 404 errors.

Does anybody can still login and get a token?

**Comment by jacobhub** [comment]
We are also experiencing this problem

**Comment by orgoldfus** [comment]
+1
Making the same request (login) using postman results in a `BadAuthentication` response.
Something has definitely changed. Either it's the url, the expected body or google public key.

**Comment by keyofd** [comment]
hi guys, as a hotfix you can try commenting out this line
https://github.com/dweinstein/node-google-play/blob/master/lib/api.js#L126

**Comment by shibataism** [comment]
@keyofd - thanks! yes this works. Just curious, but how did you find this solution? Did you randomly comment out parameters one by one?

**Comment by MisteFr** [comment]
@keyofd after commenting the line, the bulkDetails() doesn't throw any error anymore but the result is an empty array.

**Comment by MisteFr** [comment]
details() still seems to work though

**Comment by orgoldfus** [comment]
It seems like `sdk_version` parameter should be a number, not a string.
You can change this line: https://github.com/dweinstein/node-google-play/blob/ee0d651dc132f08c1a71090b121438403eced3bc/lib/api.js#L35 to number and it should work. `bulkDetails()` works as well.

**Comment by MisteFr** [comment]
@orgoldfus Login is working after you change that but bulkDetails return ['null'] as the result for me.
If you use details(), versionCode & string won't be on the result too.
So I guess the API changed to get the versionCode & string?

**Comment by orgoldfus** [comment]
@MisteFr weird. `bulkDetails()` works properly for me....

**Comment by orgoldfus** [comment]
@MisteFr this code works for me:
https://gist.github.com/orgoldfus/02829af6c03d199e97641272e46bd1f8

**Comment by orgoldfus** [comment]
Well, that's weird, but seems like it works again (without any change)

**Comment by MisteFr** [comment]
Seems everything is working back for me too
