### ISSUE TITLE
Cannot install in Windows

### ISSUE THREAD

**Issue by gowthamgts** [dweinstein/node-google-play#15]
I ran `npm install -g node-googleplay-api` and I got the following:

    > node-googleplay-api@1.1.13 postinstall C:\Users\Len\AppData\Roaming\npm\node_modules\node-googleplay-api
	> npm run get-proto

	> node-googleplay-api@1.1.13 get-proto C:\Users\Len\AppData\Roaming\npm\node_modules\node-googleplay-api
	> scripts/get_latest_proto.js

	'scripts' is not recognized as an internal or external command,
	operable program or batch file.

	npm ERR! node-googleplay-api@1.1.13 get-proto: `scripts/get_latest_proto.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the node-googleplay-api@1.1.13 get-proto script.
	npm ERR! This is most likely a problem with the node-googleplay-api package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     scripts/get_latest_proto.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls node-googleplay-api
	npm ERR! There is likely additional logging output above.
	npm ERR! System Windows_NT 6.2.9200
	npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\np
	m-cli.js" "run" "get-proto"
	npm ERR! cwd C:\Users\Len\AppData\Roaming\npm\node_modules\node-googleplay-api
	npm ERR! node -v v0.10.33
	npm ERR! npm -v 1.4.28
	npm ERR! code ELIFECYCLE
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     C:\Users\Len\AppData\Roaming\npm\node_modules\node-googleplay-api\npm-debug.log
	npm ERR! not ok code 0

	npm ERR! node-googleplay-api@1.1.13 postinstall: `npm run get-proto`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the node-googleplay-api@1.1.13 postinstall script.
	npm ERR! This is most likely a problem with the node-googleplay-api package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     npm run get-proto
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls node-googleplay-api
	npm ERR! There is likely additional logging output above.
	npm ERR! System Windows_NT 6.2.9200
	npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-googleplay-api"
	npm ERR! cwd C:\Users\Len\Desktop\area51\python-api
	npm ERR! node -v v0.10.33
	npm ERR! npm -v 1.4.28
	npm ERR! code ELIFECYCLE
	npm ERR! not ok code 0

Was it due to `protobuf`?

**Comment by dweinstein** [comment]
can you try using https://github.com/dweinstein/node-google-play/tree/issue-15 branch
