### ISSUE TITLE
i test details.test.js, but it doesn't work. error:

### ISSUE THREAD

**Issue by fengzishiren** [dweinstein/node-google-play#19]
TAP version 13
# details api
not ok 1 no error
  ---
    operator: notOk
    expected: |-
      false
    actual: |-
      { actual: false, expected: true, generatedMessage: false, message: 'not application/x-gzip response', name: 'AssertionError', operator: '==' }
    at: tryCatch1 (/home/work/linhai/node/node-googleplay/node_modules/bluebird/js/main/util.js:45:21)
  ...
not ok 2 returned results
  ---
    operator: ok
    expected: true
    actual:   undefined
    at: tryCatch1 (/home/work/linhai/node/node-googleplay/node_modules/bluebird/js/main/util.js:45:21)
  ...

1..2
# tests 2
# pass  0
# fail  2

**Comment by dweinstein** [comment]
is it possible you didn't have a username, password, android id set?
