### ISSUE TITLE
RequestError for paid apps

### ISSUE THREAD

**Issue by dweinstein** [dweinstein/node-google-play#28]
```
± gp-download-info com.mojang.minecraftpe
RequestError: The Play Store application on your device is outdated and does not support this purchase.
```

**Comment by newhouse** [comment]
Hi @dweinstein , I'm getting this error/message a lot now as well after updating to gpapi 3.4.0 to correct a different problem relate to changes in the api and what's returned by `gpap.downloadInfo()`.  Any clue if this is something that can be   solved on the gpapi side?  Or is this something where G knows about the device's Play Store version based on login device, etc?  Any help would be much appreciated!

**Comment by dweinstein** [comment]
@newhouse try checking in with a newer device / os version or with http://www.onyxbits.de/dummydroid. do you have any example package names that are failing for you? 

It may be time to collect some traces from a newer device/OS version. this library is based on a collection from an older device and app store version.

**Comment by dweinstein** [comment]
@newhouse can you retry with 3.4.1 and let me know?

**Comment by newhouse** [comment]
@dweinstein apologies for not following up. I think it's gone away now. Thanks for your continued development on this project!
