### ISSUE TITLE
Error retrieving information from server

### ISSUE THREAD

**Issue by gmobi-jacky** [dweinstein/node-google-play#30]
I could execute search.js successfully, while when I try to download a free app with download.js. It always shows an error:

Unhandled rejection RequestError: Error retrieving information from server. [DF-RPC-01]
    at handleErr (/tmp/node-google-play/lib/api.js:212:31)

**Comment by dweinstein** [comment]
@gmobi-jacky what was the package name of the application?

**Comment by cqllang** [comment]
@dweinstein 
The same error, any package names
Now is not available yet?

Unhandled rejection RequestError: Error retrieving information from server. [RH-02]

**Comment by dweinstein** [comment]
@cqllang can you double check your login/password/android ID is valid.

**Comment by cqllang** [comment]
@dweinstein  All right,I found res.statusCode is 400.
https://android.clients.google.com/fdfe/details unavailable?

**Comment by dweinstein** [comment]
@cqllang still working in tests (travis) and locally over here. how are you getting your Android ID?

**Comment by dweinstein** [comment]
I think this is likely user error. Closing until someone else is also hitting this.

**Comment by AMaini503** [comment]
I am getting the same error, although I get it using the google-play-cli. Quoting the error - "RequestError: Error retrieving information from server. [RH-02]". 

And I have double checked the login,password and android device id. For your reference, I get the device id using the app -"Device ID" by evozi.

**Comment by dweinstein** [comment]
what command are you running?

**Comment by AMaini503** [comment]
gp-download air.WatchESPN > espn.apk

**Comment by phatal** [comment]
Same error, even if trying run examples. Trying different real login-pass pairs and real device id.

**Comment by dweinstein** [comment]
try using the GSF id from the program you used to get the device id. Does it show one of those?

**Comment by dmitrypisanko** [comment]
I am receiving same error.

**Comment by cqllang** [comment]
use mitmproxy get ID and User-Agent 
set config success!

**Comment by osmanraifgunes** [comment]
I get mu apiUserAgent and downloadUserAgent by using [package capture app](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture). By getting this error : 

```
message:"Error retrieving information from server.. [DF-DFERH-01]"
name:"RequestError"
statusCode:400
```
My config is like this : 

```
var playapi = require('gpapi').GooglePlayAPI({
    username: 'mobinavel@gmail.com',
    password: '!qasdf12',
    androidId: '3300E49D5FC17767',
    countryCode:'tr',
    language:'tr_TR',
    apiUserAgent: 'Android-Finsky/xxxxxxxxxxxxxxxxxxxxxxxxx (api=3,versionCode=xxxxxxx,sdk=19,device=t03g,hardware=xxxxx,product=xxxxxx,platformVersionRelease=4.4.2,model=xxxxxxx,buildId=xxxxxx,isWideScreen=0,supportedAbis=xxxxx-v7a;xxxxx)',
    downloadUserAgent: 'AndroidDownloadManager/4.4.2 (Linux; U; Android 4.4.2; GT-xxxxx Build/xxxx)',
});
```

And request is : 

  ```
playapi.downloadInfo("com.opera.browser").then(
                    function (downloadResult, x, y, z, t) {
                        console.log(downloadResult)
                    }).catch(function (err) {
                    var a = 1;
                });
```
