### ISSUE TITLE
unauthorized after the server has been up for a while

### ISSUE THREAD

**Issue by id0Sch** [dweinstein/node-google-play#40]
Hi,
recently we started receiving an unauthorized error and we noticed that it occurs after our server has been up for a while (our server acts as a middle-man for your lib).
i remember that the login method checks if authToken exists and if it does it returns, i think that this approach causes errors since authTokens seem to expire.
i will try to figure out  a solution and maybe i will submit a PR, but i would like if you would give it attention as well...
thanks !

**Comment by id0Sch** [comment]
@dweinstein have you had the chance to look at this?

**Comment by dweinstein** [comment]
do you have an example of the error?

**Comment by dweinstein** [comment]
I created 	da4c57d to allow calling the `api.login({force: true})` to force a refresh of the authToken. Let me know if you think this will be sufficient.

**Comment by id0Sch** [comment]
i just get an unauthorized html error from google.
seems like a nice solution - thanks 👍
