### ISSUE TITLE
appCategory return null

### ISSUE THREAD

**Issue by Thomanphan** [dweinstein/node-google-play#58]
Please check appCategory  return null

**Comment by dweinstein** [comment]
I can confirm I'm seeing this as well. This wasn't the case before, so I'm not yet sure what has changed. Perhaps Google is deprecating this field.

**Comment by dweinstein** [comment]
FWIW one work around for now is to use https://www.npmjs.com/package/google-play-scraper#app which I can confirm is still returning the genre info in the response as it's scraping the webpage and not using Google's internal APIs.

**Comment by Thomanphan** [comment]
oh. Thank your information.
