### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by ahmethakanbesel** [dweinstein/node-google-play#59]
I'm getting invalid token error. How Use I script? 
var api = require('gpapi').GooglePlayAPI({
  username: example@gmail.com,
  password: @Pass123,
  androidId: EA65779211132
  // apiUserAgent: optional API agent override (see below)
  // downloadUserAgent: optional download agent override (see below)
});

**Comment by dweinstein** [comment]
try using `npm i -g google-play-cli@latest` and running `gp-get-token` after setting `ANDROID_ID`, `GOOGLE_LOGIN` and `GOOGLE_PASSWORD` as described [here](https://github.com/dweinstein/node-google-play-cli#options)
