### ISSUE TITLE
Login completely failing for 100%?

### ISSUE THREAD

**Issue by shibataism** [dweinstein/node-google-play#60]
I've seen now 100% of the login attempt gets 403 error...
Tried with multiple real accounts/devices from multiple IP addresses but no luch.

Any solution you can imagine is appreciated.

Simple way to reproduce:
```
curl -v -X POST 'https://android.clients.google.com/auth' \
-d 'Email=xxxx@gmail.com&Passwd=xxxx&androidId=xxxx&service=androidmarket&accountType=HOSTED_OR_GOOGLE&has_permission=1&source=android&app=com.android.vending&device_country=us&operatorCountry=us&sdk_version=26'
```

**Comment by yarafan** [comment]
I've got same problem

**Comment by jacobhub** [comment]
me too

**Comment by scaryzet** [comment]
It seems authenticating through EncryptedPasswd param must be implemented. There's a java project https://github.com/yeriomin/token-dispenser which is an HTTP microservice for obtaining google play store auth tokens. Currently it works fine. It encrypts the password, while node-google-play doesn't.

A useful comment in another repo about the issue: https://github.com/matlink/gplaycli/issues/80#issuecomment-313797511

The password encryption algorithm: https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/PasswordEncrypter.java

**Comment by shibataism** [comment]
@scaryzet Thanks. You are right. It seems the password encryption is the right solution for now.

BTW, does anybody has this PasswordEncrypter.java in node/ruby/python?
token-dispenser is a great microservice, but I'd prefer to have it with the languages I'm familiar with.

**Comment by sharifStrudent** [comment]
@scaryzet I changed my plain text password with encrypted result from this code: https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/PasswordEncrypter.java  but it doesn't work and Bad Authentication appear again!!!

**Comment by sharifStrudent** [comment]
@shibataism can you find a solution?

**Comment by scaryzet** [comment]
@sharifStrudent That PasswordEncrypter works fine for me. Please check you've also changed the parameter name from `Passwd` to `EncryptedPasswd`.

**Comment by subtletech** [comment]
@shibataism I've implemented the encryption in ruby: https://github.com/subtletech/google_play_store_password_encrypter

**Comment by sharifStrudent** [comment]
Thank you so much @scaryzet . after changing Passwd to EncryptedPasswd, everything is OK.

**Comment by dweinstein** [comment]
thanks guys I will implement the fix this evening or tomorrow.

**Comment by dweinstein** [comment]
fixed in 

+ gpapi@4.3.1
