### ISSUE TITLE
authToken option?

### ISSUE THREAD

**Issue by badrigopalan** [dweinstein/node-google-play#64]
I see the authToken option - could you inform how I obtain this so that I can set it? I tried getting something from the google oauth 2.0 playground, but it doesnt work (i.,e I get a RequestError in the response). Thanks!

**Comment by dweinstein** [comment]
You can use `gp-get-token` from the CLI tool https://github.com/dweinstein/node-google-play-cli

**Comment by badrigopalan** [comment]
ok, thanks. Does this auth-token work? I used the get-token to get the auth token and passed it as an option i.,e authToken: "xxx", but i get the requesterror, so perhaps this doesnt work, or I am not using it right? 


    at Promise._fulfill (/Users/badri/Projects/GPAPI/node_modules/bluebird/js/release/promise.js:638:18)
  message: '<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n',
  name: 'RequestError',
  statusCode: 401,
