### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by dmitrypisanko** [dweinstein/node-google-play#67]
Hello, i am install your module and its throw error after login.

api.details("com.viber.voip").then(console.log);

> Unhandled rejection Error
    at handleErr (node_modules/gpapi/lib/api.js:246:31)
    at node_modules/gpapi/lib/api.js:251:18
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:509:35)

**Comment by dmitrypisanko** [comment]
Request params looks ok

> { url: 'https://android.clients.google.com/fdfe/details',
  qs: { doc: 'com.viber.voip' },
  headers: 
   { 'Accept-Language': 'en_US',
     Authorization: '.......',
     'X-DFE-Enabled-Experiments': 'cl:billing.select_add_instrument_by_default',
     'X-DFE-Unsupported-Experiments': 'nocache:billing.use_charging_poller,market_emails,buyer_currency,prod_baseline,checkin.set_asset_paid_app_field,shekel_test,content_ratings,buyer_currency_in_app,nocache:encrypted_apk,recent_changes',
     'X-DFE-Device-Id': 'AD4D3D9E0CDF0F49',
     'X-DFE-Client-Id': 'am-android-google',
     'User-Agent': 'Android-Finsky/6.8.44.F-all%20%5B0%5D%203087104 (api=3,versionCode=80684400,sdk=23,device=bullhead,hardware=bullhead,product=bullhead,platformVersionRelease=6.0.1,model=Nexus%205X,buildId=MHC19Q,isWideScreen=0)',
     'X-DFE-SmallestScreenWidthDp': '320',
     'X-DFE-Filter-Level': '3',
     Host: 'android.clients.google.com',
     'X-DFE-No-Prefetch': true },
  json: false,
  gzip: false,
  encoding: null }

**Comment by yarafan** [comment]
Unhandled rejection Error means that you Promise was rejected. 
Try api.details("com.viber.voip").then(console.log).catch((err) => console.log(err)); to find out real error

**Comment by dmitrypisanko** [comment]
`{ Error
  message: 'Error retrieving information from server. [RH-02]',
  name: 'RequestError',
  statusCode: 400,
  headers: 
   { 'content-type': 'application/protobuf',
     'x-dfe-content-length': '102',
     'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     pragma: 'no-cache',
     expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
     date: 'Fri, 01 Sep 2017 10:10:11 GMT',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     server: 'GSE',
     'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,35"',
     'accept-ranges': 'none',
     vary: 'Accept-Encoding',
     connection: 'close' } }`

**Comment by yarafan** [comment]
I've got this error when I messed up with credentials info. I'd advise you to check you credentials (try to login to GP from your phone)

**Comment by dmitrypisanko** [comment]
Hi, credentials was fine. Problem was in androidID. Sorry for disturbing.
