### ISSUE TITLE
Do not download protos after package install

### ISSUE THREAD

**Issue by LegNeato** [dweinstein/node-google-play#73]
It is very weird and not very standard to download files directly from github (a gist even!) after package installation. Furthermore, this breaks when installing using a local npm repository on a machine that doesn't have outbound internet access (like, say a CI machine).

Instead I suggest one of:
* Vendoring in the contents in this repo.
* Checking the defs into a repo and making it a submodule.
* Creating a new package with just the defs and have this one mark it as a dependency.

**Comment by dweinstein** [comment]
You're right. I went ahead and created an npm package called `google-play-proto` to vendor the protobuf rather than download it via GH release.
