### ISSUE TITLE
Your device is not compatible with this item

### ISSUE THREAD

**Issue by AviFix** [dweinstein/node-google-play#79]
Hi,

Thanks for the great project.

I keep getting (a lot of times) this error: "Your device is not compatible with this item".

example package: "com.fitnesskeeper.runkeeper.pro".

Thanks
Avi

**Comment by trungducng** [comment]
@AviFix this due to the gsf-id in the config. Try to use your own gsf-id and it will work like a champ

**Comment by AviFix** [comment]
@trungducng Thanks.

I found this project: [https://github.com/onyxbits/dummydroid](url) that lets you generate id's according to what ever config / hardware you want and register them.

**Comment by dweinstein** [comment]
Was dummydroid successful for you? If so can we close this issue?

**Comment by AviFix** [comment]
Yes,
Thanks
