### ISSUE TITLE
download apk error due to wrong user_agent set

### ISSUE THREAD

**Issue by bd9142** [dweinstein/node-google-play#82]
I realized that when i try to download apk using completeDownloadInfo method, it sets user_agent to apiUserAgent. it must be downloadUserAgent to request properly. Am i wrong?

**Comment by dweinstein** [comment]
by default `completeDownloadInfo` uses the `downloadUserAgent` as can be seen https://github.com/dweinstein/node-google-play/blob/5e5eabd983a2a411d624077c5143eb3d6d84ffcb/lib/api.js#L472

Are you perhaps passing the wrong agent to the constructor?

**Comment by bd9142** [comment]
Yes you are right. However, at the end, it goes to post request and that method reset all headers as i see

**Comment by dweinstein** [comment]
`getCompleteDownloadInfo` does not make the request for you, it simply returns an object suitable for being passed to e.g., `request` lib and it does AFAICT put the `downloadUserAgent`as default user-agent. perhaps you can show your code.

**Comment by bd9142** [comment]
`
var playapi = require('gpapi').GooglePlayAPI({
	"username": "xx@gmail.com",
    "password": "xx",
    "androidId": "xx",
    "sdkVersion":23,
    "apiUserAgent": "Android-Finsky/8.8.12-all (api=3,versionCode=80881200,sdk=23,device=mp1s3gss,hardware=mp1s3gss,product=mp1s3gss_global_com,platformVersionRelease=6.0,model=LG-H542,buildId=MRA58K,isWideScreen=0,supportedAbis=armeabi-v7a;armeabi)",
    "downloadUserAgent": "AndroidDownloadManager/6.0 (Linux; U; Android 6.0; LG-H542 Build/MRA58K)"
});

playapi.details("com.mobinavel.KeepTheBall", function (err, res) {
    
 playapi.completeDownloadInfo("com.mobinavel.KeepTheBall",  res.details.appDetails.versionCode)
 .then(
    function (downloadResult, x, y, z, t) {
        console.log(downloadResult)
    }).catch(function (err, x, y, z) {
        console.log(err);
    }); 
    
 });`

this is the code that i used. firstly, i got details of app and downloaded app using version code. When i debug this code, i realized that completeDownloadInfo goes to post request and sets user-agent to apiuseragent.
