### ISSUE TITLE
401 unauthorized error after multiple requests

### ISSUE THREAD

**Issue by sampathkolanu** [dweinstein/node-google-play#83]
Hello,

1. I see 401 Unauthorized status code error after multiple requests (3 in my case).
How do I avoid this error to make unlimited requests? Is there a way I can delay the requests by limiting few requests/minute?

exact error message:

`
message: '<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n',
  name: 'RequestError',
  statusCode: 401,
  headers:
   { 'content-type': 'text/html; charset=UTF-8',
     'www-authenticate': 'GoogleLogin realm="https://accounts.google.com/ClientLogin", service="androidmarket"',
     date: 'Mon, 19 Mar 2018 01:07:35 GMT',
     expires: 'Mon, 19 Mar 2018 01:07:35 GMT',
     'cache-control': 'private, max-age=0',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     server: 'GSE',
     'alt-svc': 'hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35"',
     'accept-ranges': 'none',
     vary: 'Accept-Encoding',
     connection: 'close' } }
`

EDIT: By the way i am calling api.details and download and in my case i am making another request only after the APK file download & upload is completed 100% which will take approx. 4-5 min. Isn't 5min good amount of time for another request to the api?

2. Is the pkg param case sensitive for api.details?

Thanks

**Comment by yarafan** [comment]
Probably, the easiest way to avoid 401 is to reinitialize api,  because authorization token invalidates quickly (~2-3 min)

**Comment by sampathkolanu** [comment]
sorry for the late response, but reinitialize api worked.
Thanks @yarafan
