### ISSUE TITLE
[DF-DFERH-01] error when downloading apk

### ISSUE THREAD

**Issue by gamebenchjake** [dweinstein/node-google-play#90]
I'm getting the following error when trying to make a download request:

`RequestError: Error retrieving information from server. [DF-DFERH-01]`

I'm running the latest version of the package (4.4.1)

The code for the request is as follows:

````
private static async downloadApp(req: Request, res: Response) {
        const devId = req.params.gsfid;
        const appId = req.params.packageName;
        const ver = req.params.versioncode;
        const gpapi = require('gpapi').GooglePlayAPI({
            username: "ja*****@*******.***",
            password: "********",
            androidId: devId,
         });

         const headerContent = 'attachment; filename="' + appId + '.apk"';
         res.header('Content-Disposition', headerContent);

         return gpapi.download(appId, ver).then(function (reso: Response) {
            reso.pipe(res);
         });
}
````

Any help would be appreciated :)

**Comment by timtorChen** [comment]
Maybe you got the wrong ANDROID_ID. 
I have the same error [DF-DFERH-01] last night and find I have a worng of ANDROID_ID.

**Comment by gamebenchjake** [comment]
@timtorChen I had the write androidId, the issue was with the google account I was using; I tried a different one and it worked fine (might be due to trying to use my GSuite account)
