### ISSUE TITLE
Adding custom header support for gp

### ISSUE THREAD

**Issue by eranmit99** [dweinstein/node-google-play#92]
Hi, 
We are currently using the module to support an split APK configuration on google play. 
In order to do that and get all requesting device locals we need to add a "X-DFE-UserLanguages" to the module. 

I would like to add a custom header support for the API request. 
Is the repo still active  ? can I work on a PR ?

**Comment by eranmit99** [comment]
Hi, 
Tnx for the quick response, can u pls pump the version so I could use the fix.

**Comment by dweinstein** [comment]
for future reference you can use an unpublished version of this repo by using `dweinstein/node-google-play#commit-id" as the version and that will get you a specific commit.
