### ISSUE TITLE
bulkDetails limit

### ISSUE THREAD

**Issue by AviFix** [dweinstein/node-google-play#96]
Hi,

Thanks for the great project.

I'm trying to use the "bulkDetails" option.

On large amount of packages i get an 400 response with the following error:
`Error retrieving information from server. DF-DFERH-01`

Do you happen to know what is the limit of packages per request?

Thanks

**Comment by dweinstein** [comment]
it's somewhere close to 200

**Comment by AviFix** [comment]
Thanks
